# Generated by Django 3.0.1 on 2020-01-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_categories_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
