# Generated by Django 3.0.1 on 2020-01-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='category_slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
