# Generated by Django 3.0.1 on 2020-01-29 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_remove_topic_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
